/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ricardo
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        BotonEmpleados = new javax.swing.JButton();
        BotonObras = new javax.swing.JButton();
        BotonAsistencias = new javax.swing.JButton();
        BotonNomina = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuItemEmpleados = new javax.swing.JMenuItem();
        MenuItemObras = new javax.swing.JMenuItem();
        MenuItemAsistencias = new javax.swing.JMenuItem();
        SeparadorArchivo = new javax.swing.JPopupMenu.Separator();
        MenuItemNomina = new javax.swing.JMenuItem();
        SeparadorArchivo1 = new javax.swing.JPopupMenu.Separator();
        MenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BotonEmpleados.setText("Empleados");
        BotonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEmpleadosActionPerformed(evt);
            }
        });

        BotonObras.setText("Obras");
        BotonObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonObrasActionPerformed(evt);
            }
        });

        BotonAsistencias.setText("Asistencias");
        BotonAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAsistenciasActionPerformed(evt);
            }
        });

        BotonNomina.setText("Nomina");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonObras, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonObras, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MenuArchivo.setText("Archivo");

        MenuItemEmpleados.setText("Empleados");
        MenuItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEmpleadosActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuItemEmpleados);

        MenuItemObras.setText("Obras");
        MenuItemObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemObrasActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuItemObras);

        MenuItemAsistencias.setText("Asistencias");
        MenuItemAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAsistenciasActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuItemAsistencias);
        MenuArchivo.add(SeparadorArchivo);

        MenuItemNomina.setText("Nomina");
        MenuArchivo.add(MenuItemNomina);
        MenuArchivo.add(SeparadorArchivo1);

        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuItemSalir);

        MenuPrincipal.add(MenuArchivo);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void BotonEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEmpleadosActionPerformed
        // TODO add your handling code here:
        this.abrirEmpleados();
    }//GEN-LAST:event_BotonEmpleadosActionPerformed

    private void MenuItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEmpleadosActionPerformed
        // TODO add your handling code here:
        this.abrirEmpleados();
    }//GEN-LAST:event_MenuItemEmpleadosActionPerformed

    private void BotonObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonObrasActionPerformed
        // TODO add your handling code here:
        this.abrirObras();                
    }//GEN-LAST:event_BotonObrasActionPerformed

    private void MenuItemObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemObrasActionPerformed
        // TODO add your handling code here:
        this.abrirObras();
    }//GEN-LAST:event_MenuItemObrasActionPerformed

    private void MenuItemAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAsistenciasActionPerformed
        // TODO add your handling code here:
        this.abrirAsistencias();
    }//GEN-LAST:event_MenuItemAsistenciasActionPerformed

    private void BotonAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAsistenciasActionPerformed
        // TODO add your handling code here:
        this.abrirAsistencias();
    }//GEN-LAST:event_BotonAsistenciasActionPerformed

    public void abrirEmpleados() {
        /**
         * Este método abre la ventana empleados.
         */              
        FormEmpleados fEmpleados;        
        fEmpleados = new FormEmpleados();
        fEmpleados.setVisible(true);      
        
    } 
    
    public void abrirObras() {
        /**
         * Este método abre la ventana empleados.
         */              
        FormObras fObras;        
        fObras = new FormObras();
        fObras.setVisible(true);      
        
    } 
    
    public void abrirAsistencias() {
        /**
         * Este método abre la ventana empleados.
         */              
        FormAsistencias fAsistencias;        
        fAsistencias = new FormAsistencias();
        fAsistencias.setVisible(true);      
        
    } 
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAsistencias;
    private javax.swing.JButton BotonEmpleados;
    private javax.swing.JButton BotonNomina;
    private javax.swing.JButton BotonObras;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenuItem MenuItemAsistencias;
    private javax.swing.JMenuItem MenuItemEmpleados;
    private javax.swing.JMenuItem MenuItemNomina;
    private javax.swing.JMenuItem MenuItemObras;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JSeparator SeparadorArchivo;
    private javax.swing.JPopupMenu.Separator SeparadorArchivo1;
    // End of variables declaration//GEN-END:variables
}
